### ISSUE TITLE
Toolchain fail to compile on Debian (gcc version 7.1.0 (Debian 7.1.0-13))

### ISSUE THREAD

**Issue by MBeijer** [autc04/Retro68#25]
I get the following error while trying to compile the toolchain:
```
/home/marlon/Retro68/gcc/gcc/ubsan.c: In function ‘bool ubsan_use_new_style_p(location_t)’:
/home/marlon/Retro68/gcc/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
       || xloc.file == '\0' || xloc.file[0] == '\xff'
                       ^~~~
Makefile:1085: recipe for target 'ubsan.o' failed
make[2]: *** [ubsan.o] Error 1

```

**Comment by jduerstock** [comment]
I think the line in question should read:

`       || xloc.file[0] == '\0' || xloc.file[0] == '\xff'`

**Comment by MBeijer** [comment]
That solved the first problem, next one is following:
`  gcc -c -DHAVE_CONFIG_H -g -O2 -fstack-protector -D_FORTIFY_SOURCE=1 -fpermissive -I/usr/local/include -I. -I/home/marlon/macos-cross-toolchain/binutils/libiberty/../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE   /home/marlon/macos-cross-toolchain/binutils/libiberty/floatformat.c -o noasan/floatformat.o; \
else true; fi
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c: In function ‘fibheap_replace_key_data’:
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:38:24: error: ‘LONG_MIN’ undeclared (first use in this function)
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:220:30: note: in expansion of macro ‘FIBHEAPKEY_MIN’
   if (okey == key && okey != FIBHEAPKEY_MIN)
                              ^~~~~~~~~~~~~~
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:38:24: note: each undeclared identifier is reported only once for each function it appears in
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:220:30: note: in expansion of macro ‘FIBHEAPKEY_MIN’
   if (okey == key && okey != FIBHEAPKEY_MIN)
                              ^~~~~~~~~~~~~~
gcc -c -DHAVE_CONFIG_H -g -O2 -fstack-protector -D_FORTIFY_SOURCE=1 -fpermissive -I/usr/local/include -I. -I/home/marlon/macos-cross-toolchain/binutils/libiberty/../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D_GNU_SOURCE /home/marlon/macos-cross-toolchain/binutils/libiberty/floatformat.c -o floatformat.o
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c: In function ‘fibheap_delete_node’:
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:38:24: error: ‘LONG_MIN’ undeclared (first use in this function)
 #define FIBHEAPKEY_MIN LONG_MIN
                        ^
/home/marlon/macos-cross-toolchain/binutils/libiberty/fibheap.c:261:36: note: in expansion of macro ‘FIBHEAPKEY_MIN’
   fibheap_replace_key (heap, node, FIBHEAPKEY_MIN);
                                    ^~~~~~~~~~~~~~
cc1: warning: command line option ‘-fpermissive’ is valid for C++/ObjC++ but not for C
Makefile:753: recipe for target 'fibheap.o' failed`

**Comment by autc04** [comment]
Those problems are all in parts of gcc that I have never touched; that basically means that GCC 6.3 (wich Retro68 currently uses) can't be compiled using GCC 7.1.0.
The short term solution is of course to use an older GCC to compile; when I have the time (after my vacation is over), I'll try uprading the GCC version that Retro68 is based on again.

**Comment by MBeijer** [comment]
Weird, because I compile another cross platform toolchain that uses gcc-6.3
(amiga-m68k) without any issues on the same machine. Maybe that toolchain
has a patched binutils.

**Comment by MBeijer** [comment]
Apparently he's patched both gcc and binutils for better m68k performance:
https://github.com/bebbo/amigaos-cross-toolchain/tree/master/submodules

There's a possibility to benefit from those for this toolchain too.

**Comment by MBeijer** [comment]
Compiling the toolchain with gcc5 works on Debian, anything above doesn't work.

**Comment by autc04** [comment]
Interesting. For me, things are currently working with gcc 6.3.0 on Ubuntu, clang-800.0.421.1 on macOS Sierra, and and gcc 5.2.0.

**Comment by autc04** [comment]
I can confirm the issue for gcc 7; I can not confirm for gcc 6.3.0 on debian.

I'll try upgrading Retro68's gcc version next.

**Comment by autc04** [comment]
There's now a `ghc-7.2` branch in the repository, which should compile with gcc7. I'm still having trouble compiling it on Mac OS X / macOS, so I'll merge it after I've got that working.
Could you confirm whether that fixes your problem?

**Comment by autc04** [comment]
No further reports of this problem, it has been working for me with gcc-7.2.

I assume I can close this now.
